assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: "{version}"
  assembly_informational_version: $(appveyor_build_version)'-rc1'