//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquaConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AquaConsole.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path Not Found..
        /// </summary>
        internal static string cderrorpathnotfound {
            get {
                return ResourceManager.GetString("cderrorpathnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the current browsing directory..
        /// </summary>
        internal static string cdhelp {
            get {
                return ResourceManager.GetString("cdhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the console..
        /// </summary>
        internal static string clearhelp {
            get {
                return ResourceManager.GetString("clearhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes a command prompt command..
        /// </summary>
        internal static string cmdhelp {
            get {
                return ResourceManager.GetString("cmdhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injects an archive file into an image..
        /// </summary>
        internal static string combinehelp {
            get {
                return ResourceManager.GetString("combinehelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the input archive (with extension)..
        /// </summary>
        internal static string combineiarchive {
            get {
                return ResourceManager.GetString("combineiarchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the input image (with extension)..
        /// </summary>
        internal static string combineiimage {
            get {
                return ResourceManager.GetString("combineiimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the output image (with extension)..
        /// </summary>
        internal static string combineoimage {
            get {
                return ResourceManager.GetString("combineoimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;c&gt; 2016 GreyBlock Games. All rights reserved..
        /// </summary>
        internal static string copyrightGBG {
            get {
                return ResourceManager.GetString("copyrightGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a list of files and sub-directories in a directory..
        /// </summary>
        internal static string dirhelp {
            get {
                return ResourceManager.GetString("dirhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No argument&apos;s were supplied..
        /// </summary>
        internal static string errornoargumentssupplied {
            get {
                return ResourceManager.GetString("errornoargumentssupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) were not found, please try again....
        /// </summary>
        internal static string fileswerenotfound {
            get {
                return ResourceManager.GetString("fileswerenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to makes the application fill up the entire screen..
        /// </summary>
        internal static string fullscreentext {
            get {
                return ResourceManager.GetString("fullscreentext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays this help text..
        /// </summary>
        internal static string helphelp {
            get {
                return ResourceManager.GetString("helphelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string helpmenucommand {
            get {
                return ResourceManager.GetString("helpmenucommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =======.
        /// </summary>
        internal static string helpmenucommandborder {
            get {
                return ResourceManager.GetString("helpmenucommandborder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string helpmenuusage {
            get {
                return ResourceManager.GetString("helpmenuusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===========.
        /// </summary>
        internal static string helpmenuusageborder {
            get {
                return ResourceManager.GetString("helpmenuusageborder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opens the plugin manager screen..
        /// </summary>
        internal static string pluginmanagerhelp {
            get {
                return ResourceManager.GetString("pluginmanagerhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns a list of loaded plugins..
        /// </summary>
        internal static string pluginshelp {
            get {
                return ResourceManager.GetString("pluginshelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits the application..
        /// </summary>
        internal static string quithelp {
            get {
                return ResourceManager.GetString("quithelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts the application..
        /// </summary>
        internal static string restarthelp {
            get {
                return ResourceManager.GetString("restarthelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the console title..
        /// </summary>
        internal static string titlehelp {
            get {
                return ResourceManager.GetString("titlehelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command.
        /// </summary>
        internal static string unknowncommand {
            get {
                return ResourceManager.GetString("unknowncommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the console version..
        /// </summary>
        internal static string versionhelp {
            get {
                return ResourceManager.GetString("versionhelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, Admin privileges not detected, not all commands will work!.
        /// </summary>
        internal static string warningnotadmin {
            get {
                return ResourceManager.GetString("warningnotadmin", resourceCulture);
            }
        }
    }
}
